// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcAdbWM3WZ14tYMpeYJFaFnx5mh_IW1Eo',
    appId: '1:1060243589916:android:04c921bc1b70b121a588d9',
    messagingSenderId: '1060243589916',
    projectId: 'messenger-app-1d19e',
    storageBucket: 'messenger-app-1d19e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxWlzaGjXEau-Z6rFOn7zKgRvYNnNrIkc',
    appId: '1:1060243589916:ios:369baa76585b0fa5a588d9',
    messagingSenderId: '1060243589916',
    projectId: 'messenger-app-1d19e',
    storageBucket: 'messenger-app-1d19e.appspot.com',
    androidClientId: '1060243589916-9s9h2vvf7g3p1k8vk5esa28rsck98nih.apps.googleusercontent.com',
    iosClientId: '1060243589916-u97jlqnln8hoovlgcujcd3su6f84hfvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingApp',
  );
}
